#![doc = include_str!("../README.md")]
#![no_std]

use core::mem;

/// Due to the lack of stable `concat_idents`, we need a small proc macro
pub use mident;

/// Trait that can be auto-implemented on a `#[repr(C, uX)]` enum
///
/// This trait is unsafe to manually implement because the types need to match up properly:
/// [DiscriminantTy](Self::DiscriminantTy) needs to have the same `repr` as our tag,
/// and both need to have the same discriminant counts, and neither can have custom discriminant values.
pub unsafe trait EnumHelped {
    /// The (1-1) corresponding [EnumDiscriminant] autogenerated type for this enum
    type DiscriminantTy: EnumDiscriminant;

    /// The number of variants this enum has
    const NUM_VARIANTS: u128 = Self::DiscriminantTy::NUM_VARIANTS;

    #[inline(always)]
    /// Convert this enum value to just a bare discriminant
    fn as_discriminant(&self) -> Self::DiscriminantTy {
        unsafe {
            // SAFETY: A #[repr(C, uX)] enum starts with a tag of type `uX`,
            // which is compatible with the repr of DiscriminantTy,
            // and both of these have the exact same discriminant counts and values.
            let self_ = self as *const Self as *const Self::DiscriminantTy;
            *self_
        }
    }

    #[inline(always)]
    /// Convert the enum discriminant to a raw integer
    fn as_int(&self) -> <Self::DiscriminantTy as EnumDiscriminant>::ReprTy {
        self.as_discriminant().as_int()
    }
}

/// Trait that can be auto-implemented on the corresponding discriminant enum
///
/// This trait is unsafe to manually implement because
/// the type actually needs to have the repr of [ReprTy](Self::ReprTy),
/// the discriminant count must be correct, and there cannot be custom discriminant values.
pub unsafe trait EnumDiscriminant: Copy {
    /// The number of variants this enum has
    const NUM_VARIANTS: u128;

    /// The raw integer type for this enum discriminant
    ///
    /// This can be one of Rust's primitive integer types
    type ReprTy: Copy + core::convert::Into<u128>;

    /// The (1-1) corresponding original enum type
    type FancyTy: EnumHelped<DiscriminantTy = Self>;

    #[inline(always)]
    /// Convert the enum discriminant to a raw integer
    fn as_int(&self) -> Self::ReprTy {
        unsafe {
            // SAFETY: We must be a `#[repr(uX)]` enum
            // Ideally we'd not need unsafe here, but this is unavoidable in a generic context.
            debug_assert_eq!(mem::size_of::<Self>(), mem::size_of::<Self::ReprTy>());
            let self_ = self as *const Self as *const Self::ReprTy;
            *self_
        }
    }

    #[inline(always)]
    /// Convert the enum discriminant from a raw integer
    ///
    /// Panics if the integer is out-of-range
    fn from_int(x: Self::ReprTy) -> Self {
        let x_128: u128 = x.into();
        if x_128 >= Self::NUM_VARIANTS {
            panic!("enum variant {} out of range", x_128);
        }
        debug_assert_eq!(mem::size_of::<Self>(), mem::size_of::<Self::ReprTy>());
        // SAFETY: We must be a `#[repr(uX)]` enum,
        // with the expected number of variants, and without gaps in the discriminant values.
        // This note also applies to the following functions.
        unsafe { mem::transmute_copy(&x) }
    }

    #[inline(always)]
    /// Convert the enum discriminant from a raw integer
    ///
    /// Returns a default value if the integer is out-of-range
    fn from_int_or_default(x: Self::ReprTy) -> Self
    where
        Self::FancyTy: Default,
    {
        let x_128: u128 = x.into();
        if x_128 >= Self::NUM_VARIANTS {
            return Self::FancyTy::default().as_discriminant();
        }
        debug_assert_eq!(mem::size_of::<Self>(), mem::size_of::<Self::ReprTy>());
        unsafe { mem::transmute_copy(&x) }
    }

    #[inline(always)]
    /// Convert the enum discriminant from a raw integer
    ///
    /// Returns `None` if the integer is out-of-range
    fn try_from_int(x: Self::ReprTy) -> Option<Self> {
        let x_128: u128 = x.into();
        if x_128 >= Self::NUM_VARIANTS {
            return None;
        }
        debug_assert_eq!(mem::size_of::<Self>(), mem::size_of::<Self::ReprTy>());
        unsafe { Some(mem::transmute_copy::<_, Self>(&x)) }
    }
}

/// Helper trait for converting enums to integers in a generic and dyn-compatible way
///
/// There are automatic built-in impls that allow coercion to same-or-larger integers of the same signed-ness.
pub trait TypeErasedDynEnumAsInt<IntTy> {
    fn as_any_int(&self) -> IntTy;
}

macro_rules! impl_type_erase {
    ($sz:ident) => {
        impl<
            R: ::core::convert::Into<$sz>,
            D: EnumDiscriminant<ReprTy = R>,
            E: EnumHelped<DiscriminantTy = D>,
        > TypeErasedDynEnumAsInt<$sz> for E
        {
            fn as_any_int(&self) -> $sz {
                self.as_discriminant().as_int().into()
            }
        }
    };
}

impl_type_erase!(u8);
impl_type_erase!(i8);
impl_type_erase!(u16);
impl_type_erase!(i16);
impl_type_erase!(u32);
impl_type_erase!(i32);
impl_type_erase!(u64);
impl_type_erase!(i64);
impl_type_erase!(u128);
impl_type_erase!(i128);
impl_type_erase!(usize);
impl_type_erase!(isize);

/// Auto-implement enum helper traits (while correctly counting variants)
///
/// Usage is as follows:
/// ```rust
/// # use enum_c_helper::enum_c_helper;
/// enum_c_helper! {
///     #[repr(C, u8)]  // This line _must_ be first
///     /// Other attrs, such as doc comments, are allowed
///     #[derive(Copy, Clone, Debug)]   // So are derives
///     enum ExampleEnum {
///         VariantOne,                         // The usual C-compatible
///         VariantTwo(u8, u16),                // tagged enum contents
///         VariantThree { x: u32, y: u32 },    // are permitted here
///         // NotAllowed = 123,                // ... but *not* custom discriminant values
///     }
/// }
/// ```
#[macro_export]
macro_rules! enum_c_helper {
    (
        #[repr(C, $c_repr:ty)]
        $(#[$($attr:tt)*])*
        $vis:vis enum $id:ident {
            $($var:ident $(( $($parens:tt)* ))? $({ $($bracketed:tt)* })?),* $(,)?
        }
    ) => {
        #[repr(C, $c_repr)]
        $(#[$($attr)*])*
        $vis enum $id {
            $($var $(( $($parens)* ))? $({ $($bracketed)* })?,)*
        }

        $crate::mident::mident! {
            #[doc = ::core::concat!("Autogenerated discriminant type for [", ::core::stringify!($id), "]")]
            #[allow(unused)]
            #[repr($c_repr)]
            #[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Debug, Hash)]
            $vis enum #concat($id Discriminant) {
                $($var,)*
            }

            unsafe impl $crate::EnumHelped for $id {
                type DiscriminantTy = #concat($id Discriminant);
            }

            unsafe impl $crate::EnumDiscriminant for #concat($id Discriminant) {
                const NUM_VARIANTS: u128 = 0 $( + {
                    let _dummy = ::core::stringify!($var);
                    1
                })*;
                type ReprTy = $c_repr;
                type FancyTy = $id;
            }
        }
    };
}

#[cfg(test)]
mod tests {
    use super::*;

    enum_c_helper! {
        #[repr(C, u8)]
        /// Test doc comment
        #[allow(unused)]
        enum TestEnum {
            VariantOne,
            VariantTwo(u8, u16),
            VariantThree { x: u32, y: u32 },
        }
    }
    impl Default for TestEnum {
        fn default() -> Self {
            Self::VariantTwo(69, 420)
        }
    }

    #[test]
    fn test_num_variants() {
        assert_eq!(<TestEnum as EnumHelped>::DiscriminantTy::NUM_VARIANTS, 3);
    }

    #[test]
    fn test_to_discriminant() {
        assert!(matches!(
            TestEnum::VariantOne.as_discriminant(),
            TestEnumDiscriminant::VariantOne
        ));

        assert!(matches!(
            TestEnum::VariantTwo(123, 12345).as_discriminant(),
            TestEnumDiscriminant::VariantTwo
        ));

        assert!(matches!(
            TestEnum::VariantThree { x: 11111, y: 22222 }.as_discriminant(),
            TestEnumDiscriminant::VariantThree
        ));
    }

    #[test]
    fn test_to_int() {
        assert!(matches!(TestEnum::VariantOne.as_int(), 0u8));

        assert!(matches!(TestEnum::VariantTwo(123, 12345).as_int(), 1u8));

        assert!(matches!(
            TestEnum::VariantThree { x: 11111, y: 22222 }.as_int(),
            2u8
        ));
    }

    #[test]
    fn test_from_int() {
        assert!(matches!(<_>::from_int(0), TestEnumDiscriminant::VariantOne));
        assert!(matches!(<_>::from_int(1), TestEnumDiscriminant::VariantTwo));
        assert!(matches!(
            <_>::from_int(2),
            TestEnumDiscriminant::VariantThree
        ));
    }

    #[test]
    #[should_panic(expected = "enum variant 3 out of range")]
    fn test_from_int_bad() {
        matches!(<_>::from_int(3), TestEnumDiscriminant::VariantOne);
    }

    #[test]
    fn test_from_int_fallible() {
        assert!(TestEnumDiscriminant::try_from_int(3).is_none());
    }

    #[test]
    fn test_from_int_default() {
        assert!(matches!(
            <_>::from_int_or_default(3),
            TestEnumDiscriminant::VariantTwo
        ));
    }

    #[test]
    fn test_type_erased_as_int() {
        let _x: u8 = TestEnum::VariantOne.as_any_int();
        let _x: u16 = TestEnum::VariantOne.as_any_int();
        let _x: u32 = TestEnum::VariantOne.as_any_int();
        let _x: u64 = TestEnum::VariantOne.as_any_int();
    }
}
